name: Kath Drever Photography
favicon: null
layout_spectrum: 0.98153
typography_spectrum: 0.30468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111212'
    - '#ffffff'
    - '#ae8080'
    - '#d91d47'
    - '#833a1e'
  brandStrength: 0.4375
  lightness: 0.8795069875195622
  saturation: 0.21326381620019674
  rhythmicContrast: 0.087402218952775
purpose: []
