analytics: {}
color:
  brandColors:
    - '#111212'
    - '#ffffff'
    - '#ae8080'
    - '#d91d47'
    - '#833a1e'
  brandStrength: 0.530405
  lightness: 0.477196
  rhythmicContrast: 0.380912
  saturation: 0.015203
cta: {}
layout_spectrum: 0.98153
name: Kath Drever Photography
opengraph: {}
purpose: []
typography_spectrum: 0.30468
